-- https://school.programmers.co.kr/learn/courses/30/lessons/301646

-- 풀이
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE 
BIN(GENOTYPE) = 1  OR
BIN(GENOTYPE) = 01 OR
( 
  LENGTH(BIN(GENOTYPE)) >= 3 AND 
  SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)) -1, 1) != 1 AND
  (SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)) -2, 1) = 1 OR SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)), 1) = 1 ) 
)